#!/bin/bash
sudo /etc/init.d/mysql start
sudo mysql -uroot -e "CREATE DATABASE IF NOT EXISTS webdb;"
sudo mysql -uroot -e "CREATE USER 'webuser'@'localhost' IDENTIFIED BY '12345678';"
sudo mysql -uroot -e "GRANT ALL PRIVILEGES ON webdb.* TO 'webuser'@'localhost';"
sudo mysql -uroot -e "FLUSH PRIVILEGES;"

cd ask
python3 manage.py makemigrations
python3 manage.py migrate